scheduler:
  image:
    repository: "gcr.io/dask-demo-182016/dask-tutorial-worker"
    tag: "2c5045"
  resources:
    limits:
      cpu: 1.8
      memory: 6G
    requests:
      cpu: 1.8
      memory: 6G
  env:
    - name: DASK_WORKER_MEMORY_TARGET
      value: "1.0"

worker:
  image:
    repository: "gcr.io/dask-demo-182016/dask-tutorial-worker"
    tag: "2c5045"
  replicas: 10
  resources:
    limits:
      cpu: 4
      memory: 12.8G
    requests:
      cpu: 3.5
      memory: 12.8G
  env:
    - name: DASK_WORKER_MEMORY_TARGET
      value: "1.0"

jupyter:
  image:
    repository: "gcr.io/dask-demo-182016/dask-tutorial-notebook"
    tag: "2c5045"
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'  # 'dask'
  resources:
    limits:
      cpu: 2
      memory: 6G
    requests:
      cpu: 2
      memory: 6G
